/*
 * Mahdi Salimkhani

 */
package com.salimkhani.javapaint;
import com.salimkhani.javapaint.application.PaintingArea;
import com.salimkhani.javapaint.application.Shape;
import com.salimkhani.javapaint.application.Point;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import org.javatuples.Pair;


/**
 *
 * @author mahdi
 */
public class PaintingPanel extends javax.swing.JPanel {
    private final PaintingArea pArea;

    /**
     * Creates new form PaintingPanel
     */
    public PaintingPanel() {
        pArea = PaintingArea.New(getHeight(), getWidth());
        initComponents();
    }

    @Override
    protected Graphics getComponentGraphics(Graphics g) {
        return super.getComponentGraphics(g);
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        try {
            pArea.reDrawAll(g);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void drawComponent(Shape s)
    {
        pArea.addShape(s);
        repaint();
        //s.draw(getGraphics());
    }
    public void removeComponet(Shape s)
    {
        pArea.removeShape(s);
        repaint();
    }
    public void pushComponentToFront(Shape s)
    {
        pArea.removeShape(s);
        pArea.addShape(s);
        repaint();
    }
    public void zoomInComponent(Shape s)
    {
        try {
            s.zoomIn(1.1);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public Pair<Boolean, Shape> selectComponent(Point p)
    {
        for (int i = pArea.shapeArr.size()-1; i >= 0; i--) {
            Shape s = pArea.shapeArr.get(i);
            if(s.select(getGraphics(), p))
            {
                return new Pair<>(true, s);
            }
        }
        return new Pair<>(false, null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
